name: "Build Engine"
on:
  release:
    types: [published]
jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write  # Needed for release upload
    steps:
      - name: "Checkout files"
        uses: actions/checkout@v4

      - name: Download Thirdparty
        shell: powershell
        run: |
          $wc = New-Object System.Net.WebClient
          $wc.DownloadFile("https://www.panda3d.org/download/panda3d-1.10.14/panda3d-1.10.14-tools-win64.zip", "thirdparty-tools.zip")
          Add-Type -Assembly "System.IO.Compression.Filesystem"
          [System.IO.Compression.ZipFile]::ExtractToDirectory("thirdparty-tools.zip", "thirdparty-tools")
          Move-Item -Path thirdparty-tools/panda3d-1.10.14/thirdparty -Destination .

      - name: Build Panda
        shell: powershell
        run: |        
          .\thirdparty\win-python3.11-x64\python.exe makepanda\makepanda.py `
            --installer `
            --wheel `
            --optimize 3 `
            --lzma `
            --threads=4 `
            --nothing `
            --use-python `
            --use-direct `
            --use-gl `
            --use-gles `
            --use-gles2 `
            --use-tinydisplay `
            --use-nvidiacg `
            --use-egl `
            --use-eigen `
            --use-openal `
            --use-vorbis `
            --use-opus `
            --use-ffmpeg `
            --use-swscale `
            --use-swresample `
            --use-ode `
            --use-pandaphysics `
            --use-zlib `
            --use-png `
            --use-jpeg `
            --use-squish `
            --use-assimp `
            --use-egg `
            --use-freetype `
            --use-harfbuzz `
            --use-openssl `
            --use-directcam `
            --use-vision `
            --use-pandatool `
            --use-pview `
            --use-deploytools `
            --use-skel `
            --use-pandafx `
            --use-pandaparticlesystem `
            --use-contrib `
            --use-sse2 `
            --use-neon `
            --use-toontown `
            --msvc-version=14.3 `
            --windows-sdk=10

      - name: Upload Panda Binaries
        shell: powershell
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.ref_name }} Panda3D-1.11.0-py3.11-x64.exe
          gh release upload ${{ github.ref_name }} panda3d-1.11.0-cp311-cp311-win_amd64.whl

  build-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for release upload
    steps:
      - name: Checkout files
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y \
            build-essential \
            libassimp-dev \
            libeigen3-dev \
            libgl1-mesa-dev \
            libjpeg-dev \
            libode-dev \
            libpng-dev \
            libsquish-dev \
            libssl-dev \
            patchelf \
            pkg-config

      - name: Build Panda
        run: |
          python makepanda/makepanda.py \
            --wheel \
            --optimize 3 \
            --lzma \
            --threads=4 \
            --nothing \
            --use-python \
            --use-direct \
            --use-gl \
            --use-tinydisplay \
            --use-egl \
            --use-eigen \
            --use-ode \
            --use-pandaphysics \
            --use-zlib \
            --use-png \
            --use-jpeg \
            --use-squish \
            --use-assimp \
            --use-egg \
            --use-openssl \
            --use-directcam \
            --use-skel \
            --use-pandaparticlesystem \
            --use-contrib \
            --use-sse2 \
            --use-toontown \
            --python-incdir="$pythonLocation/include" \
            --python-libdir="$pythonLocation/lib"

      - name: Upload Panda Binary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.ref_name }} panda3d-1.11.0-cp311-cp311-linux_x86_64.whl
